server:
  port: 8081

spring:
  h2:
    console:
      enabled: 'true'
      path: /h2-console
      

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
